global using System;
global using System.Threading.Tasks;
global using System.IO;
global using System.Diagnostics;
global using System.Collections.Generic;
global using System.Linq;
global using System.Threading;

global using IOFile = System.IO.File;
global using IOPath = System.IO.Path;

global using File.Commander.Extensions;
global using File.Commander.Presentation.ViewModels.Shell;
global using File.Commander.Presentation.Views.Shell;
global using File.Commander.Presentation.ViewModels;
global using File.Commander.Application.IDialogService;
global using File.Commander.Application.Plugins;
global using File.Commander.Domain.Config;
global using File.Commander.PluginCatalog;
global using File.Commander.Presentation.ViewModels.Plugin;
global using File.Commander.Application.Keyboard;
global using File.Commander.Application.Settings;
global using File.Commander.Application.Updates;
global using File.Commander.Presentation.Services;
global using File.Commander.Presentation.ViewModels.ActionCenter;
global using File.Commander.Presentation.Views.Settings;
global using File.Commander.Presentation.ViewModels.Dialogs;
global using File.Commander.Presentation.ViewModels.Settings;
global using File.Commander.Presentation.Views.Dialogs;
global using File.Commander.Presentation.Themes;
global using File.Commander.Plugins;
global using File.Commander.Presentation.ViewModels.Helpers;
global using File.Commander.Presentation.ViewModels.Pages;
global using File.Commander.Application.Operations;
global using File.Commander.Application.FileSystem;
global using File.Commander.Presentation.ViewModels.Browser;
global using File.Commander.Presentation.ViewModels.Info;
global using File.Commander.Application.Path;
global using File.Commander.Presentation.ViewModels.Computer;
global using File.Commander.Presentation.Views.Browser;
global using File.Commander.Presentation.ViewModels.Network;
global using File.Commander.Presentation.Views.Network;